### ISSUE TITLE
展示页面，条目显示bug 

### ISSUE THREAD

**Issue by brownfoxsir** [newpanjing/simpleui#365]
**bug描述**
点进页面详情，明明一个都没选，就会显示所有的数量已经选定，清除选中
![image](https://user-images.githubusercontent.com/38450626/115201601-18193100-a128-11eb-8307-a30ba72cabbd.png)

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

**重现步骤**
1.当前页面查询的数据数量必须足够大，50个一下好像不会显示，我的设置每页显示50，超过50的时候就会显示出“所有数量已经选定，清除选中

**环境**
** environment**

1.Operating System：
_MAC OS_

2.Python Version：
_python3.8.5_

3.Django Version：
_django3.2_
4.SimpleUI Version：
_2021.4.1_

**Description**

**Comment by brownfoxsir** [comment]
这个是django3.2改变了分页策略， 修改下底层模板就好了

**Comment by brownfoxsir** [comment]
> 老哥，你这第一页显示不？我这每次第一页都显示不了，点击第一页又跳转到第二页，然后有几条数据都显示不了🌝

这个是django3.2改变了分页策略， 修改下底层模板就好了

**Comment by Allo-0** [comment]
老哥
你说的是改这里吗？


红色箭头这俩处吗？
我改了也没用.....................



老哥，能不能指点一下.



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "newpanjing/simpleui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月9日(星期天) 晚上11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [newpanjing/simpleui] 展示页面，条目显示bug  (#365)





 
这个是django3.2改变了分页策略， 修改下底层模板就好了

**Comment by brownfoxsir** [comment]
> 老哥
> 你说的是改这里吗？
> 
> 
> 红色箭头这俩处吗？
> 我改了也没用.....................
> 
> 
> 
> 老哥，能不能指点一下.
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人:                                                                                                                        "newpanjing/simpleui"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2021年5月9日(星期天) 晚上11:30
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [newpanjing/simpleui] 展示页面，条目显示bug  (#365)
> 
> 
> 
> 
> 
>  
> 这个是django3.2改变了分页策略， 修改下底层模板就好了
>  
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

MIKE  
{% load admin_list %}
{% load i18n %}
{% load simpletags %}
<div id="pagination">
    {% if pagination_required %}
        <el-pagination
                background
                @current-change="handleCurrentChange"
                :current-page="{{ cl.page_num }}"                
                :page-size="{{ cl.list_per_page }}"
                layout="total,prev, pager, next"
                :total="{{ cl.result_count|to_str }}">
        </el-pagination>
    {% endif %}
</div>
<script type="text/javascript">
    $(function () {
        new Vue({
            el: "#pagination",
            data: {},
            methods: {
                handleCurrentChange:function (page) {
                    page_go(page);
                }
            }
        })

        function page_go(p) {
            $("#changelist-search input[name='p']").val(p);
            $("#changelist-search").submit();
        }

    });
</script>

**Comment by Allo-0** [comment]
老哥，我是一个新手，我试着把分页的那一页html信息全删了，留一个空文件，保存以后，还是能正常显示我那个后台网页，这是bug吗？我怀疑我那个django项目有问题，所以改了分页的html文件的参数它也不会同步。尽管我开了debug模式。这种情况你遇到过没？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "newpanjing/simpleui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 晚上10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [newpanjing/simpleui] 展示页面，条目显示bug  (#365)





  
老哥
 你说的是改这里吗？
 
红色箭头这俩处吗？
 我改了也没用.....................
 
老哥，能不能指点一下.
 
------------------ 原始邮件 ------------------
 发件人:                                                                                                                        "newpanjing/simpleui"                                                                                    @.&gt;;
 发送时间:&nbsp;2021年5月9日(星期天) 晚上11:30
 @.&gt;;
 @.@.&gt;;
 主题:&nbsp;Re: [newpanjing/simpleui] 展示页面，条目显示bug  (#365)
 
这个是django3.2改变了分页策略， 修改下底层模板就好了
 
—
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub, or unsubscribe.
  
MIKE
 {% load admin_list %}
 {% load i18n %}
 {% load simpletags %}
      {% if pagination_required %}                       {% endif %} 
 <script type="text/javascript"&gt;     $(function () {         new Vue({             el: "#pagination",             data: {},             methods: {                 handleCurrentChange:function (page) {                     page_go(page);                 }             }         })     function page_go(p) {         $("#changelist-search input[name='p']").val(p);         $("#changelist-search").submit();     } });  </script&gt;

**Comment by brownfoxsir** [comment]
> 老哥，我是一个新手，我试着把分页的那一页html信息全删了，留一个空文件，保存以后，还是能正常显示我那个后台网页，这是bug吗？我怀疑我那个django项目有问题，所以改了分页的html文件的参数它也不会同步。尽管我开了debug模式。这种情况你遇到过没？
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "newpanjing/simpleui"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2021年5月10日(星期一) 晚上10:06
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [newpanjing/simpleui] 展示页面，条目显示bug  (#365)
> 
> 
> 
> 
> 
>   
> 老哥
>  你说的是改这里吗？
>  
> 红色箭头这俩处吗？
>  我改了也没用.....................
>  
> 老哥，能不能指点一下.
>  
> ------------------ 原始邮件 ------------------
>  发件人:                                                                                                                        "newpanjing/simpleui"                                                                                    @.&gt;;
>  发送时间:&nbsp;2021年5月9日(星期天) 晚上11:30
>  @.&gt;;
>  @.@.&gt;;
>  主题:&nbsp;Re: [newpanjing/simpleui] 展示页面，条目显示bug  (#365)
>  
> 这个是django3.2改变了分页策略， 修改下底层模板就好了
>  
> —
>  You are receiving this because you commented.
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>   
> MIKE
>  {% load admin_list %}
>  {% load i18n %}
>  {% load simpletags %}
>       {% if pagination_required %}                       {% endif %} 
>  <script type="text/javascript"&gt;     $(function () {         new Vue({             el: "#pagination",             data: {},             methods: {                 handleCurrentChange:function (page) {                     page_go(page);                 }             }         })     function page_go(p) {         $("#changelist-search input[name='p']").val(p);         $("#changelist-search").submit();     } });  </script&gt; 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

你可能搞错了。。。。。

**Comment by bode135** [comment]
...我也遇到了, 解决了吗

**Comment by brownfoxsir** [comment]
> ...我也遇到了, 解决了吗

这个不知道新版解决了没，我是修改了tmeplate解决了
